//Teste de requisições - Posição

@baseURL = http://localhost:4000
@id = 60a9ee4ca22e18529aa000d4
###
//GET - Lista as Posições
GET {{baseURL}}/posicoes
Content-Type: application/json

###
//GET - Lista a Posição pelo ID
GET {{baseURL}}/posicoes/{{id}}
Content-Type: application/json

###
// POST - Inclui uma nova posição
POST {{baseURL}}/posicoes
Content-Type: application/json

{"nome": "Lateral Esquerdo", "status": "ativo"}

###
// DELETE - Apaga uma posição
DELETE {{baseURL}}/posicoes/{{id}}
Content-Type: application/json

###
// PUT - Altera a posição
PUT {{baseURL}}/posicoes
Content-Type: application/json

{
"_id" : "",
"nome" : "",
"status" : "ativo"
}